### PR TITLE
Password confirmation optional

### PR DESCRIPTION
**Pull request by BiJason**
Entering "Current password' is optional outside of changing user email/password. 

--Additional fix in this pull request: password confirmation(the field wouldn't matter before) for editting is properly working.

### CODE REVIEW

**Review by quichey — COMMENTED** [review]
cool solution to not requiring a password

**Review by quichey — COMMENTED** [review]
any way we could make the test coverage same as before?

**Review by quichey — COMMENTED** [review]
maybe add tests for when a user changes their password or email? and tests for when a user changes a different field? whichever is missing

**Comment by ckvan** [comment]
Make sure you've re-pulled from master again and check the index.html file for lines of code to be covered (open it up in a browser).

**Comment by ckvan** [comment]
I had the same issue/scare. When I ran cucumber, I got a lower percentage. Then I ran rake, got 99.23% as expected, then ran cucumber again to get expected %

**Pull request merged**
